### ISSUE TITLE
'View All Tags (F7)' does not work if there are multiple identical tags with different case(upper/lower)

### ISSUE THREAD

**Issue by yanne** [yanne/api-testing#137]
Using RIDE 1.3.0 and python 2.7.3.

I'm loading an extensive test directory, some tags are uppercased, some are lowercased. Sometimes the same tag is used uppercase and lowercase(due to different committers, not saying this is a good idea, but it happens).

View all tags doesn't work in this case.

This is in the log:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\ui\actiontriggers.py", line 379, in **call**
    action.act(event)
  File "C:\Python27\lib\site-packages\robotide\action\action.py", line 86, in act
    self.action(event)
  File "C:\Python27\lib\site-packages\robotide\utils\eventhandler.py", line 22, in wrapped
    method(self, event)
  File "C:\Python27\lib\site-packages\robotide\ui\mainframe.py", line 248, in OnViewAllTags
    self._view_all_tags_dialog.show_dialog()
  File "C:\Python27\lib\site-packages\robotide\ui\tagdialogs.py", line 114, in show_dialog
    self._execute()
  File "C:\Python27\lib\site-packages\robotide\ui\tagdialogs.py", line 92, in _execute
    self._search_for_tags()
  File "C:\Python27\lib\site-packages\robotide\ui\tagdialogs.py", line 139, in _search_for_tags
    self._tagit[tag_name].append(tag)
KeyError: u'Under_construction'

This issue was originally reported to <a href="http://code.google.com/p/robotframework-ride/issues/detail?id=1330">Google Code</a> on Feb 19, 2014.

**Comment by yanne** [comment]
Original comment by `mikko.ko...@gmail.com` on Mar 10, 2014.

(No comment was entered for this change.)
